language: cpp
dist: trusty
osx_image: xcode9.4

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=RelWithDebInfo

jobs:
  allow_failures:
    - compiler: gcc
      os: osx


before_script:
  - mkdir -p build && cd build
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=$HOME/.local -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/; else cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=$HOME/.local; fi
  - cd ..

script:
  - cd build && cmake --build . && cd ..
  - make test