language: cpp
dist: trusty
osx_image: xcode9.4

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=RelWithDebInfo

jobs:
  allow_failures:
    - compiler: gcc
      os: osx


before_script:
  - mkdir -p build && cd build
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then OPENSSL_PATH="-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/"; fi
  - FLAGS="-DCMAKE_BUILD_TYPE=$BUILD_TYPE $OPENSSL_PATH"
  - cmake .. -G "Unix Makefiles" $FLAGS
  - cd ..

script:
  - cd build && cmake --build . && cd ..
